apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-staging
  labels:
    name: hello-world-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-production
  labels:
    name: hello-world-production