-- Database Schema Migration
-- Generated by OneClickOps Spec Agent

-- Table: mobile_devices
CREATE TABLE IF NOT EXISTS mobile_devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  platform VARCHAR(10) NOT NULL,
  device_id VARCHAR(255) NOT NULL,
  device_name VARCHAR(100) NOT NULL,
  push_token TEXT,
  app_version VARCHAR(20),
  os_version VARCHAR(50),
  timezone VARCHAR(50),
  last_active TIMESTAMP,
  registered_at TIMESTAMP NOT NULL DEFAULT NOW(),
  biometric_enabled BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_mobile_devices_user_id ON mobile_devices (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mobile_devices_device_id ON mobile_devices (device_id);
CREATE INDEX IF NOT EXISTS idx_mobile_devices_push_token ON mobile_devices (push_token);

-- Table: biometric_keys
CREATE TABLE IF NOT EXISTS biometric_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id UUID NOT NULL,
  biometric_type VARCHAR(20) NOT NULL,
  public_key TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_used TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_biometric_keys_device_id ON biometric_keys (device_id);

-- Table: offline_sync_log
CREATE TABLE IF NOT EXISTS offline_sync_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id UUID NOT NULL,
  action_type VARCHAR(50) NOT NULL,
  action_data JSONB NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  synced BOOLEAN NOT NULL DEFAULT false,
  synced_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_offline_sync_log_device_id ON offline_sync_log (device_id);
CREATE INDEX IF NOT EXISTS idx_offline_sync_log_synced ON offline_sync_log (synced);
CREATE INDEX IF NOT EXISTS idx_offline_sync_log_timestamp ON offline_sync_log (timestamp);

