-- Database Schema Migration
-- Generated by OneClickOps Spec Agent

-- Table: users
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  email_verified BOOLEAN NOT NULL,
  email_verification_token VARCHAR(255),
  password_reset_token VARCHAR(255),
  password_reset_expires TIMESTAMP,
  preferences JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_email_verification_token ON users (email_verification_token);
CREATE INDEX IF NOT EXISTS idx_users_password_reset_token ON users (password_reset_token);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at);

-- Table: user_sessions
CREATE TABLE IF NOT EXISTS user_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  refresh_token_hash VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at TIMESTAMP,
  user_agent TEXT,
  ip_address INET
);

CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_sessions_refresh_token_hash ON user_sessions (refresh_token_hash);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions (expires_at);

-- Table: languages
CREATE TABLE IF NOT EXISTS languages (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  extension VARCHAR(10) NOT NULL,
  category VARCHAR(50) NOT NULL,
  icon VARCHAR(255),
  popularity INTEGER NOT NULL,
  syntax_highlighting VARCHAR(50) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_languages_category ON languages (category);
CREATE INDEX IF NOT EXISTS idx_languages_popularity ON languages (popularity);
CREATE INDEX IF NOT EXISTS idx_languages_active ON languages (active);

-- Table: function_templates
CREATE TABLE IF NOT EXISTS function_templates (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  language_id VARCHAR(50) NOT NULL,
  difficulty VARCHAR(20) NOT NULL,
  category VARCHAR(50) NOT NULL,
  template TEXT NOT NULL,
  example TEXT,
  tags TEXT[],
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_function_templates_language_id ON function_templates (language_id);
CREATE INDEX IF NOT EXISTS idx_function_templates_difficulty ON function_templates (difficulty);
CREATE INDEX IF NOT EXISTS idx_function_templates_category ON function_templates (category);
CREATE INDEX IF NOT EXISTS idx_function_templates_active ON function_templates (active);

-- Table: saved_functions
CREATE TABLE IF NOT EXISTS saved_functions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  language_id VARCHAR(50) NOT NULL,
  code TEXT NOT NULL,
  customizations JSONB,
  tags TEXT[],
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_saved_functions_user_id ON saved_functions (user_id);
CREATE INDEX IF NOT EXISTS idx_saved_functions_language_id ON saved_functions (language_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_saved_functions_user_id_name ON saved_functions (user_id, name);
CREATE INDEX IF NOT EXISTS idx_saved_functions_created_at ON saved_functions (created_at);
CREATE INDEX IF NOT EXISTS idx_saved_functions_updated_at ON saved_functions (updated_at);
CREATE INDEX IF NOT EXISTS idx_saved_functions_tags ON saved_functions (tags);

-- Table: shared_functions
CREATE TABLE IF NOT EXISTS shared_functions (
  id VARCHAR(50) PRIMARY KEY,
  code TEXT NOT NULL,
  language_id VARCHAR(50) NOT NULL,
  customizations JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  view_count INTEGER NOT NULL,
  created_by_user_id UUID
);

CREATE INDEX IF NOT EXISTS idx_shared_functions_language_id ON shared_functions (language_id);
CREATE INDEX IF NOT EXISTS idx_shared_functions_expires_at ON shared_functions (expires_at);
CREATE INDEX IF NOT EXISTS idx_shared_functions_created_at ON shared_functions (created_at);
CREATE INDEX IF NOT EXISTS idx_shared_functions_created_by_user_id ON shared_functions (created_by_user_id);

-- Table: user_activity
CREATE TABLE IF NOT EXISTS user_activity (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  action VARCHAR(50) NOT NULL,
  resource_type VARCHAR(50),
  resource_id VARCHAR(100),
  metadata JSONB,
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_activity_user_id ON user_activity (user_id);
CREATE INDEX IF NOT EXISTS idx_user_activity_action ON user_activity (action);
CREATE INDEX IF NOT EXISTS idx_user_activity_created_at ON user_activity (created_at);
CREATE INDEX IF NOT EXISTS idx_user_activity_user_id_created_at ON user_activity (user_id, created_at);

